spring:
  application:
    name: peya-kata
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always
    jpa:
      hibernate:
        ddl-auto: create-drop

server:
  port: 8080
  error:
    include-message: always

db:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/peya_kata?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    maxLifetime: 420000
    idleTimeout: 60000
    maximumPoolSize: 200
    leakDetectionThreshold: 0
    prepStmtCacheSize: 250
    cachePrepStmts: true
    cacheServerConfiguration: true
    connectionTimeout: 30000
    minimumIdle: 25